/**
 * 
 */
package edu.springboot.a2z.emporg.entity;

import java.time.ZonedDateTime;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

import edu.springboot.a2z.emporg.util.OrgUtil;

/**
 * @author NextGenAZ
 *
 */

@Entity
@Table(name="emp")
public class Emp {
	
	@Id
	//@GeneratedValue(strategy = GenerationType.AUTO)	//Tells the field is auto generated by the database and not provided by user
	//@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "empno")
	private Integer empNo;

	@Column(name = "ename")
	private String eName;
	
	@Column(name = "job")
	private String job;
	
	@Column(name = "mgr")
	private String manager;
	
	@Column(name = "hiredate")
	private ZonedDateTime hireDate;
	
	@Column(name = "sal")
	private Float salary;
	
	@Column(name = "comm")
	private Float commission;
	
	@Column(name = "deptno")
	private Integer deptNo;
	
	public Emp() {
		super();
	}
	
	public Emp(Integer empNo, String eName, String job, String manager, ZonedDateTime hireDate, Float salary, Float commission, Integer deptNo) {
		this.empNo = empNo;
		this.eName = eName;
		this.job = job;
		this.manager = manager;
		this.hireDate = hireDate;
		this.salary = salary;
		this.commission = commission;
		this.deptNo = deptNo;
	}
	
	/*
	public Emp(String eName, String job, String manager, String hireDate, Float salary, Float commission, Integer deptNo) {
		this.eName = eName;
		this.job = job;
		this.manager = manager;
		this.hireDate = hireDate;
		this.salary = salary;
		this.commission = commission;
		this.deptNo = deptNo;
	}
	*/

	public Integer getEmpNo() {
		return empNo;
	}

	public void setEmpNo(Integer empNo) {
		this.empNo = empNo;
	}

	public String geteName() {
		return eName;
	}

	public void seteName(String eName) {
		this.eName = eName;
	}

	public String getJob() {
		return job;
	}

	public void setJob(String job) {
		this.job = job;
	}

	public String getManager() {
		return manager;
	}

	public void setManager(String manager) {
		this.manager = manager;
	}

	public ZonedDateTime getHireDate() {
		return hireDate;
	}

	public void setHireDate(String hireDate) {
		this.hireDate = OrgUtil.getDateFromString(hireDate);
	}

	public Float getSalary() {
		return salary;
	}

	public void setSalary(Float salary) {
		this.salary = salary;
	}

	public Float getCommission() {
		return commission;
	}

	public void setCommission(Float commission) {
		this.commission = commission;
	}

	public Integer getDeptNo() {
		return deptNo;
	}

	public void setDeptNo(Integer deptNo) {
		this.deptNo = deptNo;
	}
	
	
	
}
